name: DO wblk wk1
on:
  push:
    branches: [ main ]
jobs:
  master_deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set current_timestamp
      run: |
          echo "current_timestamp=`date '+%y%m%d%H%M%S'`" >> $GITHUB_ENV
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        version: 1
    - name: Laravel mix
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: |
          npm i
          npm run prod
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: buildlk.com
        username: achala
        key: ${{secrets.DO_SSH}}
        port: 22
        source: "."
        target: "/var/www/buildlk.com/releases/${{ env.current_timestamp }}"
    - name: Creating symlink
      uses: appleboy/ssh-action@master
      with: 
        host: buildlk.com
        username: achala
        key: ${{secrets.DO_SSH}}
        port: 22
        script: |
          ln -sfn /var/www/buildlk.com/releases/${{ env.current_timestamp }} /var/www/buildlk.com/public_html
          ln -sfn /var/www/buildlk.com/.env /var/www/buildlk.com/public_html/.env
          rm -r /var/www/buildlk.com/releases/${{ env.current_timestamp }}/storage
          ln -sfn /var/www/buildlk.com/storage /var/www/buildlk.com/releases/${{ env.current_timestamp }}/storage
          cd /var/www/buildlk.com/releases/${{ env.current_timestamp }} && php artisan storage:link
