name: Verify PR
on: 
  pull_request:
    branches:
      - master

jobs:
  verify: 
    if: github.event.pull_request.draft == false
    name: verify
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set current_timestamp
      run: |
          echo "current_timestamp=`date '+%y%m%d%H%M%S'`" >> $GITHUB_ENV
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        version: 1
    - name: Laravel mix
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: |
          npm i
          npm run prod
  
